name: Build

on:
  workflow_call:
    inputs:
      DOCKERHUB_USER:
        type: string
        required: true
        description: "DockerHub username"
    secrets:
      DOCKERHUB_PASSWORD:
        required: true
        description: "DockerHub password"

env:
  DOCKER_TAG: docker.io/${{ vars.DOCKERHUB_USER }}/github-calculator:${{ github.ref_name }}-${{ github.sha }}

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_TAG }}